### ISSUE TITLE
我可以在本地运行这个游戏吗

### ISSUE THREAD

**Issue by ISDHN** [hellochar/mito#105]
如果我没有连接互联网,但是把这个库下载了,可以运行吗?  
如果可以,如何运行?

**Comment by hellochar** [comment]
I will be adding a mito exe/dmg file in the future. In the meantime you are welcome to clone this repo and run it yourself from the README instructions.

**Comment by ISDHN** [comment]
OK.  
Thank you very much.:-)

**Comment by hellochar** [comment]
You're welcome :) I'd appreciate it if you joined the discord - you can give feedback about what you like/dislike about the game, and share any ideas! 

https://discord.gg/N8wWwPX
