### ISSUE TITLE
no limit on genes

### ISSUE THREAD

**Issue by deepledi** [hellochar/mito#97]
did this by just just putting as many useful genes on tissue as possible. weird how genes like soil absorption and photosynthesis stack
![image](https://user-images.githubusercontent.com/33794610/77604811-ff185f00-6ed8-11ea-89a8-bb465581534f.png)

**Comment by deepledi** [comment]
maybe a hard limit could work?

**Comment by Dexapnow** [comment]
So cancer it is

**Comment by hellochar** [comment]
Hey @deepledi , thanks for playing and providing feedback. In the past week I've added a "cancer" mechanic to try and mitigate the "god cell" strategy.

Mito is still in early development and I'd appreciate it if you joined the discord - https://discord.gg/EbVYkqW thanks!

**Comment by hellochar** [comment]
I've changed how this works now; genes cannot be stacked.
