### ISSUE TITLE
Unneded/lots of genes

### ISSUE THREAD

**Issue by Dexapnow** [hellochar/mito#98]
I have found having many genes an really anoying things since having many of them on one cell streches list and they don't stack.
I suggest adding some kind of inventory/stacking (if having same type and level of gene) or just way to upgrade genes by adding the same type and level on them.

**Comment by hellochar** [comment]
Thanks for the feedback; mind sharing me a screenshot of what your cells look like? Most things should stack (e.g. multiple photosyntheses)

Mito is still in early development and I'd appreciate it if you joined the discord - https://discord.gg/EbVYkqW thanks!
